### ISSUE TITLE
when set model = 'none', can not login contrail web with admin/contrail123

### ISSUE THREAD

**Issue by jason4wy** [Juniper/contrail-web-core#270]
04/25/2017 02:44:17 AM - ^[[31merror^[[39m: URL [http://127.0.0.1:8081/analytics/uves/control-node] returned error ["Authentication required"]
04/25/2017 02:44:17 AM - ^[[31merror^[[39m: Encountered broken link: /analytics/uves/control-node
04/25/2017 02:44:17 AM - ^[[31merror^[[39m: REST Server Error: Authentication required
    at APIServer.retryMakeCall (/var/lib/contrail-webui/contrail-web-core/src/serverroot/common/rest.api.js:203:13)
    at Request.<anonymous> (/var/lib/contrail-webui/contrail-web-core/src/serverroot/common/rest.api.js:336:18)
    at Request.emit (events.js:98:17)
    at Request.mixin._fireSuccess (/var/lib/contrail-webui/node_modules/restler/lib/restler.js:226:10)
    at /var/lib/contrail-webui/node_modules/restler/lib/restler.js:157:20
    at IncomingMessage.parsers.auto (/var/lib/contrail-webui/node_modules/restler/lib/restler.js:390:7)
    at Request.mixin._encode (/var/lib/contrail-webui/node_modules/restler/lib/restler.js:194:29)
    at /var/lib/contrail-webui/node_modules/restler/lib/restler.js:153:16
    at Request.mixin._decode (/var/lib/contrail-webui/node_modules/restler/lib/restler.js:169:7)
    at IncomingMessage.<anonymous> (/var/lib/contrail-webui/node_modules/restler/lib/restler.js:146:14)
04/25/2017 02:44:18 AM - ^[[34mdebug^[[39m: We got the channel:98a7d5e6-dba1-4023-bde7-98a15e6df467 by process:1535

**Comment by biswajit-mandal** [comment]
In case orchestration model "none", you need to disable multi_tenancy (pre R3.2) or need to set aaa_mode to no-auth(R3.2 and later) both in contrail-api.conf and contrail-analytics-api.conf file, else you will get the authentication error, as it tries to do token validation with keystone.

**Comment by jason4wy** [comment]
thanks

**Comment by jason4wy** [comment]
hi,  not find the configuration in both in contrail-api.conf and contrail-analytics-api.conf file.   can you post your conf files at here?

**Comment by jason4wy** [comment]
thanks , it is okay now.
