### ISSUE TITLE
when executing contrail.sh install, script dev-install.sh failed

### ISSUE THREAD

**Issue by Groundsea** [Juniper/contrail-web-core#272]
Hi,

After contrail.sh install finished, I found some issues in install log. I'm not sure it is correlation with web-core. The log is like below:

2017-07-16 09:53:35 make[1]: Entering directory `/opt/stack/contrail/contrail-web-core'
2017-07-16 09:53:35 rm -f src/serverroot/jobs/core/jobsCb.api.js
2017-07-16 09:53:35 rm -f src/serverroot/web/core/feature.list.js
2017-07-16 09:53:35 rm -f src/serverroot/web/routes/url.routes.js
2017-07-16 09:53:35 rm -rf node_modules
2017-07-16 09:53:35 rm -rf webroot/assets
2017-07-16 09:53:35 make[1]: Leaving directory `/opt/stack/contrail/contrail-web-core'
2017-07-16 09:53:35 rm -rf node_modules
2017-07-16 09:53:35 mkdir -p node_modules
2017-07-16 09:53:35 cp -rf '../contrail-webui-third-party'/node_modules/* node_modules/.
2017-07-16 09:53:35 ++ make dev-env REPO=webController
2017-07-16 09:53:35 mkdir -p webroot/html
2017-07-16 09:53:35 ln -sf ../../webroot/html/dashboard.tmpl webroot/html/dashboard.html
2017-07-16 09:53:35 ln -sf ../../webroot/html/login.tmpl webroot/html/login.html
2017-07-16 09:53:35 ln -sf ../../webroot/html/login-error.tmpl webroot/html/login-error.html
2017-07-16 09:53:35 if [ ! -d ../controller ]; then make fetch-schema; fi
2017-07-16 09:53:35 ./generate-files.sh "dev-env" webController
2017-07-16 09:53:36 dir.readFiles error for Dir:/opt/stack/contrail/contrail-web-core/src/tools/../..:null
2017-07-16 09:53:36 dir.readFiles error for Dir:/opt/stack/contrail/contrail-web-controller:null
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/common/api/feature.list.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/common/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-core/src/serverroot/common/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/common/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/dns/records/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/dns/servers/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-core/src/serverroot/jobs/core/jobsCb.api.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-core/src/serverroot/utils/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/firewall/common/fwpolicy/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-core/src/serverroot/web/core/feature.list.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-core/src/serverroot/web/routes/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/infra/bgp/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/infra/linklocalservices/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/infra/quotas/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-core/webroot/reports/qe/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/infra/serviceappliance/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-core/webroot/reports/udd/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/infra/serviceapplianceset/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/infra/vrouters/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/networking/fip/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/networking/ipam/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/networking/logicalrouter/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/networking/networks/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/networking/policy/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/networking/port/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/networking/routetable/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/networking/routingpolicy/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/networking/securitygroup/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/physicaldevices/interfaces/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/physicaldevices/physicalrouters/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/port/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/services/bgpasaservice/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/services/instances/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/infrastructure/controlnode/jobs/jobsCb.api.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/config/services/templates/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/infrastructure/analyticsnode/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/infrastructure/vrouter/jobs/jobsCb.api.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/infrastructure/confignode/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/networking/jobs/jobsCb.api.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/infrastructure/controlnode/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/infrastructure/databasenode/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/infrastructure/globalcontroller/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/infrastructure/underlay/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/infrastructure/vrouter/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/monitor/networking/api/url.routes.js
2017-07-16 09:53:36 Done, creating file: /opt/stack/contrail/contrail-web-controller/webroot/setting/configdb/ui/api/url.routes.js
2017-07-16 09:53:37 Done!
2017-07-16 09:53:37 Schemas generated under directory: configJsonSchemas
2017-07-16 09:53:37 Copied json schema files to src/serverroot/configJsonSchemas
2017-07-16 09:53:37 ./dev-install.sh
2017-07-16 09:53:37 
2017-07-16 09:53:37 module.js:340
2017-07-16 09:53:37     throw err;
2017-07-16 09:53:37           ^
2017-07-16 09:53:37 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:37     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:37     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:37     at require (module.js:380:17)
2017-07-16 09:53:37     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:37     at Module._compile (module.js:456:26)
2017-07-16 09:53:37     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:37     at Module.load (module.js:356:32)
2017-07-16 09:53:37     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:37 
2017-07-16 09:53:37 module.js:340
2017-07-16 09:53:37     throw err;
2017-07-16 09:53:37           ^
2017-07-16 09:53:37 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:37     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:37     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:37     at require (module.js:380:17)
2017-07-16 09:53:37     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:37     at Module._compile (module.js:456:26)
2017-07-16 09:53:37     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:37     at Module.load (module.js:356:32)
2017-07-16 09:53:37     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:37 
2017-07-16 09:53:37 module.js:340
2017-07-16 09:53:37     throw err;
2017-07-16 09:53:37           ^
2017-07-16 09:53:37 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:37     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:37     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:37     at require (module.js:380:17)
2017-07-16 09:53:37     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:37     at Module._compile (module.js:456:26)
2017-07-16 09:53:37     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:37     at Module.load (module.js:356:32)
2017-07-16 09:53:37     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:37 
2017-07-16 09:53:37 module.js:340
2017-07-16 09:53:37     throw err;
2017-07-16 09:53:37           ^
2017-07-16 09:53:37 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:37     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:37     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:37     at require (module.js:380:17)
2017-07-16 09:53:37     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:37     at Module._compile (module.js:456:26)
2017-07-16 09:53:37     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:37     at Module.load (module.js:356:32)
2017-07-16 09:53:37     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:37 
2017-07-16 09:53:37 module.js:340
2017-07-16 09:53:37     throw err;
2017-07-16 09:53:37           ^
2017-07-16 09:53:37 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:37     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:37     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:37     at require (module.js:380:17)
2017-07-16 09:53:37     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:37     at Module._compile (module.js:456:26)
2017-07-16 09:53:37     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:37     at Module.load (module.js:356:32)
2017-07-16 09:53:37     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:37     at Module.require (module.js:364:17)
2017-07-16 09:53:38 
2017-07-16 09:53:38 module.js:340
2017-07-16 09:53:38     throw err;
2017-07-16 09:53:38           ^
2017-07-16 09:53:38 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:38     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:38     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38     at require (module.js:380:17)
2017-07-16 09:53:38     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:38     at Module._compile (module.js:456:26)
2017-07-16 09:53:38     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:38     at Module.load (module.js:356:32)
2017-07-16 09:53:38     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38 
2017-07-16 09:53:38 module.js:340
2017-07-16 09:53:38     throw err;
2017-07-16 09:53:38           ^
2017-07-16 09:53:38 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:38     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:38     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38     at require (module.js:380:17)
2017-07-16 09:53:38     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:38     at Module._compile (module.js:456:26)
2017-07-16 09:53:38     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:38     at Module.load (module.js:356:32)
2017-07-16 09:53:38     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38 
2017-07-16 09:53:38 module.js:340
2017-07-16 09:53:38     throw err;
2017-07-16 09:53:38           ^
2017-07-16 09:53:38 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:38     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:38     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38     at require (module.js:380:17)
2017-07-16 09:53:38     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:38     at Module._compile (module.js:456:26)
2017-07-16 09:53:38     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:38     at Module.load (module.js:356:32)
2017-07-16 09:53:38     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38 
2017-07-16 09:53:38 module.js:340
2017-07-16 09:53:38     throw err;
2017-07-16 09:53:38           ^
2017-07-16 09:53:38 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:38     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:38     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38     at require (module.js:380:17)
2017-07-16 09:53:38     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:38     at Module._compile (module.js:456:26)
2017-07-16 09:53:38     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:38     at Module.load (module.js:356:32)
2017-07-16 09:53:38     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38 
2017-07-16 09:53:38 module.js:340
2017-07-16 09:53:38     throw err;
2017-07-16 09:53:38           ^
2017-07-16 09:53:38 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:38     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:38     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38     at require (module.js:380:17)
2017-07-16 09:53:38     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:38     at Module._compile (module.js:456:26)
2017-07-16 09:53:38     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:38     at Module.load (module.js:356:32)
2017-07-16 09:53:38     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38 
2017-07-16 09:53:38 module.js:340
2017-07-16 09:53:38     throw err;
2017-07-16 09:53:38           ^
2017-07-16 09:53:38 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:38     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:38     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38     at require (module.js:380:17)
2017-07-16 09:53:38     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:38     at Module._compile (module.js:456:26)
2017-07-16 09:53:38     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:38     at Module.load (module.js:356:32)
2017-07-16 09:53:38     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38 
2017-07-16 09:53:38 module.js:340
2017-07-16 09:53:38     throw err;
2017-07-16 09:53:38           ^
2017-07-16 09:53:38 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:38     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:38     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38     at require (module.js:380:17)
2017-07-16 09:53:38     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:38     at Module._compile (module.js:456:26)
2017-07-16 09:53:38     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:38     at Module.load (module.js:356:32)
2017-07-16 09:53:38     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38 
2017-07-16 09:53:38 module.js:340
2017-07-16 09:53:38     throw err;
2017-07-16 09:53:38           ^
2017-07-16 09:53:38 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:38     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:38     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:38     at require (module.js:380:17)
2017-07-16 09:53:38     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:38     at Module._compile (module.js:456:26)
2017-07-16 09:53:38     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:38     at Module.load (module.js:356:32)
2017-07-16 09:53:38     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:38     at Module.require (module.js:364:17)
2017-07-16 09:53:39 
2017-07-16 09:53:39 module.js:340
2017-07-16 09:53:39     throw err;
2017-07-16 09:53:39           ^
2017-07-16 09:53:39 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:39     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:39     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39     at require (module.js:380:17)
2017-07-16 09:53:39     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:39     at Module._compile (module.js:456:26)
2017-07-16 09:53:39     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:39     at Module.load (module.js:356:32)
2017-07-16 09:53:39     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39 
2017-07-16 09:53:39 module.js:340
2017-07-16 09:53:39     throw err;
2017-07-16 09:53:39           ^
2017-07-16 09:53:39 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:39     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:39     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39     at require (module.js:380:17)
2017-07-16 09:53:39     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:39     at Module._compile (module.js:456:26)
2017-07-16 09:53:39     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:39     at Module.load (module.js:356:32)
2017-07-16 09:53:39     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39 
2017-07-16 09:53:39 module.js:340
2017-07-16 09:53:39     throw err;
2017-07-16 09:53:39           ^
2017-07-16 09:53:39 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:39     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:39     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39     at require (module.js:380:17)
2017-07-16 09:53:39     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:39     at Module._compile (module.js:456:26)
2017-07-16 09:53:39     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:39     at Module.load (module.js:356:32)
2017-07-16 09:53:39     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39 
2017-07-16 09:53:39 module.js:340
2017-07-16 09:53:39     throw err;
2017-07-16 09:53:39           ^
2017-07-16 09:53:39 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:39     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:39     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39     at require (module.js:380:17)
2017-07-16 09:53:39     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:39     at Module._compile (module.js:456:26)
2017-07-16 09:53:39     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:39     at Module.load (module.js:356:32)
2017-07-16 09:53:39     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39 
2017-07-16 09:53:39 module.js:340
2017-07-16 09:53:39     throw err;
2017-07-16 09:53:39           ^
2017-07-16 09:53:39 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:39     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:39     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39     at require (module.js:380:17)
2017-07-16 09:53:39     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:39     at Module._compile (module.js:456:26)
2017-07-16 09:53:39     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:39     at Module.load (module.js:356:32)
2017-07-16 09:53:39     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39 
2017-07-16 09:53:39 module.js:340
2017-07-16 09:53:39 Downloading cassanadra
2017-07-16 09:53:39     throw err;
2017-07-16 09:53:39           ^
2017-07-16 09:53:39 Error: Cannot find module 'scss-tokenizer'
2017-07-16 09:53:39     at Function.Module._resolveFilename (module.js:338:15)
2017-07-16 09:53:39     at Function.Module._load (module.js:280:25)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39     at require (module.js:380:17)
2017-07-16 09:53:39     at Object.<anonymous> (/opt/stack/contrail/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
2017-07-16 09:53:39     at Module._compile (module.js:456:26)
2017-07-16 09:53:39     at Object.Module._extensions..js (module.js:474:10)
2017-07-16 09:53:39     at Module.load (module.js:356:32)
2017-07-16 09:53:39     at Function.Module._load (module.js:312:12)
2017-07-16 09:53:39     at Module.require (module.js:364:17)
2017-07-16 09:53:39 Reading package lists...
2017-07-16 09:53:39 make: *** [dev-env] Error 8

Is it some environment setting error?

**Comment by Groundsea** [comment]
Sorry, it is for the network problem. some node modules didn't download successfully.
