### ISSUE TITLE
Error Fetch Packages Python

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [Juniper/contrail-web-core#273]
Hi, i try to install contrail web UI.
and when i run the instalation tutorial

`make fetch-pkgs-dev make dev-env REPO=webController`

I get some error. I this the error is in the fetch_packages in line 92

> Traceback (most recent call last):
>   File "../contrail-webui-third-party/fetch_packages.py", line 354, in <module>
>     main(xmlfile)
>   File "../contrail-webui-third-party/fetch_packages.py", line 334, in main
>     ProcessPackage(object)
>   File "../contrail-webui-third-party/fetch_packages.py", line 314, in ProcessPackage
>     ApplyPatches(pkg)
>   File "../contrail-webui-third-party/fetch_packages.py", line 92, in ApplyPatches
>     proc = subprocess.Popen(cmd, stdin = fp)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> make: *** [fetch-pkgs-dev] Error 1

this is the fungtion that cause the error, anyone know?

> def ApplyPatches(pkg):
>     stree = pkg.find('patches')
>     if stree is None:
>         return
>     for patch in stree.getchildren():
>         cmd = ['patch']
>         if patch.get('strip'):
>             cmd.append('-p')
>             cmd.append(patch.get('strip'))
>         if _OPT_VERBOSE:
>             print "Patching %s <%s..." % (' '.join(cmd), str(patch))
>         if not _OPT_DRY_RUN:
>             fp = open(str(patch), 'r')
>             proc = subprocess.Popen(cmd, stdin = fp)
>             proc.communicate()

this is not the first error i get when running this python file.
the first error is in the 
> def getZipDestination(tgzfile):
>     cmd = subprocess.Popen(['unzip', '-t', tgzfile],
>                            stdout=subprocess.PIPE)
>     (output, _) = cmd.communicate()
>     lines = output.split('\n')
>     for line in lines:
>         print line
>         m = re.search(r'testing:\s+([\w\-\.]+)\/', line)
>         if m:
>             return m.group(1)
>     return None

i fix that error by install unzip packages.

**Comment by zufardhiyaulhaq** [comment]
Fix it by installing unzip and patch
yum install unzip patch
